source 'https://github.com/CocoaPods/Specs.git'
inhibit_all_warnings!
#use_frameworks!

platform :ios, '8.0'

target 'MVVM_RAC' do
    pod 'ReactiveCocoa',    '~> 2.5’
    pod 'YYWebImage'
    pod 'MJRefresh'
    pod 'MJExtension'
    pod 'TUNetworking'
    pod 'SVProgressHUD'
end